### ISSUE TITLE
Trouble getting Blahtex working with ruby 2.3.0

### ISSUE THREAD

**Issue by poulsbo** [parasew/instiki#32]
With a stock build, I get errors within Maruku. Instead of trying to fix these one at a time, I tried using the latest Maruku. This doesn't work at all.

Lots of mysterious "Expired fragment" statements, followed by:

```
 ___________________________________________________________________________
| Maruku tells you:
+---------------------------------------------------------------------------
| Blahtex error: empty output
+---------------------------------------------------------------------------
!/app/vendor/bundle/ruby/2.3.0/gems/maruku-0.7.2/lib/maruku/ext/math/mathml_engines/blahtex.rb:32:in `convert_to_png_blahtex'
!/app/vendor/bundle/ruby/2.3.0/gems/maruku-0.7.2/lib/maruku/ext/math/to_html.rb:69:in `render_png'
!/app/vendor/bundle/ruby/2.3.0/gems/maruku-0.7.2/lib/maruku/ext/math/to_html.rb:106:in `to_html_inline_math'
!/app/vendor/bundle/ruby/2.3.0/gems/maruku-0.7.2/lib/maruku/output/to_html.rb:891:in `block in array_to_html'
\___________________________________________________________________________
```

And indeed, the math rendering is empty. It looks like:

```
<span class='maruku-inline'></span>
```

**Comment by distler** [comment]
Sounds like a problem with your Blahtex installation.

(Just curious: why do you prefer blahtex to itex2mml+MathJax ?)

**Comment by poulsbo** [comment]
I've been happily using itex2mml+MathJax but I wanted to see if Blahtex
would yield more consistent rendering. Depending on browser, I see minor
rendering issues, such as overlapping subscript characters.

**Comment by poulsbo** [comment]
I think this might be restricted to ruby 2.3.0. When I use ruby 2.2.4, I get a different error, which looks like a Blahtex / TeX Live configuration error on my part:

```
$ echo '\alpha' | blahtex --png --use-preview-package --shell-dvipng 'dvipng -D 200'
<blahtex>
<png>
<error><id>CannotRunLatex</id><message>Cannot run latex</message></error>
</png>
</blahtex>
```

Versus:

```
$ echo '\alpha' | blahtex --png                                                     
<blahtex>
<png>
<md5>930ecc82d87425b6b0d18eabeca22ed9</md5>
</png>
</blahtex>
```
