### ISSUE TITLE
Error on start after installation

### ISSUE THREAD

**Issue by SL-RU** [parasew/instiki#36]
linux: debian jessie

```
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [armv7l-linux-eabihf]
```
```
@instiki$ ruby bundle install --path vendor/bundle
Using rake 10.4.2
Using RedCloth 4.3.2
Using abstract 1.0.0
Using daemons 1.2.3
Using erubis 2.7.0
Using eventmachine 1.2.0.1
Using file_signature 1.2.0
Using iconv 1.0.4
Using itextomml 1.5.2
Using json 1.8.3
Using nokogiri 1.5.11
Using syntax 1.1.0
Using rack 2.0.1
Using rails_xss 0.4.0
Using rubyzip 0.9.9
Using sqlite3 1.3.11
Using test-unit 2.5.5
Using bundler 1.11.2
Using rdoc 4.2.2
Using maruku 0.7.3.beta1 from git://github.com/distler/maruku.git (at nokogiri@c67cc83)
Using thin 1.7.0
Bundle complete! 19 Gemfile dependencies, 21 gems now installed.
Bundled gems are installed into ./vendor/bundle.
@instiki$ ruby instiki
=> Booting Thin
=> Rails 2.3.18 application starting on http://0.0.0.0:2500
instiki/vendor/plugins/bundler/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir instiki/vendor/bundle/ruby/2.3.0/bin in PATH, mode 040777
instiki/vendor/plugins/bundler/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir  instiki/vendor/bundle/ruby/2.3.0/bin in PATH, mode 040777
=> Call with -d to detach
=> Ctrl-C to shutdown server
Thin web server (v1.7.0 codename Dunder Mifflin)
Maximum connections set to 1024
Listening on 0.0.0.0:2500, CTRL+C to stop
/!\ FAILSAFE /!\  2016-07-11 22:04:32 +0000
  Status: 500 Internal Server Error
  wrong number of arguments (given 2, expected 1)
     instiki/vendor/rails/actionpack/lib/action_controller/request.rb:518:in `parse_query'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/request.rb:319:in `GET'
     instiki/vendor/rails/actionpack/lib/action_controller/request.rb:426:in `GET'
     instiki/vendor/rails/actionpack/lib/action_controller/request.rb:385:in `parameters'
     instiki/vendor/rails/actionpack/lib/action_controller/base.rb:1290:in `assign_shortcuts'
     instiki/vendor/rails/actionpack/lib/action_controller/base.rb:527:in `process'
     instiki/vendor/rails/actionpack/lib/action_controller/filters.rb:606:in `process_with_filters'
     instiki/vendor/rails/actionpack/lib/action_controller/rescue.rb:65:in `call_with_exception'
     instiki/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:90:in `rescue in dispatch'
     instiki/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:96:in `dispatch'
     instiki/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:121:in `_call'
     instiki/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:130:in `block in build_middleware_stack'
     instiki/vendor/rails/activerecord/lib/active_record/query_cache.rb:29:in `block in call'
     instiki/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
     instiki/vendor/rails/activerecord/lib/active_record/query_cache.rb:9:in `cache'
     instiki/vendor/rails/activerecord/lib/active_record/query_cache.rb:28:in `call'
     instiki/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
     instiki/vendor/rails/actionpack/lib/action_controller/string_coercion.rb:25:in `call'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
     instiki/vendor/rails/actionpack/lib/action_controller/params_parser.rb:15:in `call'
     instiki/vendor/rails/railties/lib/rails/rack/metal.rb:47:in `call'
     instiki/vendor/rails/actionpack/lib/action_controller/session/cookie_store.rb:99:in `call'
     instiki/vendor/rails/actionpack/lib/action_controller/failsafe.rb:26:in `call'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/lock.rb:15:in `call'
     instiki/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:106:in `call'
     instiki/vendor/rails/railties/lib/rails/rack/static.rb:31:in `call'
     instiki/vendor/rails/railties/lib/rails/rack/log_tailer.rb:17:in `call'
     instiki/vendor/rails/railties/lib/rails/rack/static.rb:31:in `call'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:68:in `block in call'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `each'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `call'
     instiki/vendor/rails/railties/lib/rails/rack/log_tailer.rb:17:in `call'
     instiki/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'
     instiki/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'
     instiki/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'
     instiki/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:53:in `process'
     instiki/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:39:in `receive_data'
     instiki/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
     instiki/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
     instiki/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/backends/base.rb:73:in `start'
     instiki/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/server.rb:162:in `start'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/handler/thin.rb:22:in `run'
     instiki/script/server:119:in `<top (required)>'
    instiki:6:in `load'
    instiki:6:in `<main>'
/!\ FAILSAFE /!\  2016-07-11 22:04:32 +0000
  Status: 500 Internal Server Error
  wrong number of arguments (given 2, expected 1)
     instiki/vendor/rails/actionpack/lib/action_controller/request.rb:518:in `parse_query'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/request.rb:319:in `GET'
     instiki/vendor/rails/actionpack/lib/action_controller/request.rb:426:in `GET'
     instiki/vendor/rails/actionpack/lib/action_controller/request.rb:385:in `parameters'
     instiki/vendor/rails/actionpack/lib/action_controller/base.rb:1290:in `assign_shortcuts'
     instiki/vendor/rails/actionpack/lib/action_controller/base.rb:527:in `process'
     instiki/vendor/rails/actionpack/lib/action_controller/filters.rb:606:in `process_with_filters'
     instiki/vendor/rails/actionpack/lib/action_controller/rescue.rb:65:in `call_with_exception'
     instiki/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:90:in `rescue in dispatch'
     instiki/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:96:in `dispatch'
     instiki/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:121:in `_call'
     instiki/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:130:in `block in build_middleware_stack'
     instiki/vendor/rails/activerecord/lib/active_record/query_cache.rb:29:in `block in call'
     instiki/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
     instiki/vendor/rails/activerecord/lib/active_record/query_cache.rb:9:in `cache'
     instiki/vendor/rails/activerecord/lib/active_record/query_cache.rb:28:in `call'
     instiki/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
     instiki/vendor/rails/actionpack/lib/action_controller/string_coercion.rb:25:in `call'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
     instiki/vendor/rails/actionpack/lib/action_controller/params_parser.rb:15:in `call'
     instiki/vendor/rails/railties/lib/rails/rack/metal.rb:47:in `call'
     instiki/vendor/rails/actionpack/lib/action_controller/session/cookie_store.rb:99:in `call'
     instiki/vendor/rails/actionpack/lib/action_controller/failsafe.rb:26:in `call'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/lock.rb:15:in `call'
     instiki/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:106:in `call'
     instiki/vendor/rails/railties/lib/rails/rack/static.rb:31:in `call'
     instiki/vendor/rails/railties/lib/rails/rack/log_tailer.rb:17:in `call'
     instiki/vendor/rails/railties/lib/rails/rack/static.rb:31:in `call'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:68:in `block in call'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `each'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `call'
     instiki/vendor/rails/railties/lib/rails/rack/log_tailer.rb:17:in `call'
     instiki/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'
     instiki/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'
     instiki/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'
     instiki/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:53:in `process'
     instiki/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:39:in `receive_data'
     instiki/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
     instiki/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
     instiki/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/backends/base.rb:73:in `start'
     instiki/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/server.rb:162:in `start'
     instiki/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/handler/thin.rb:22:in `run'
     instiki/script/server:119:in `<top (required)>'
    instiki:6:in `load'
    instiki:6:in `<main>'
^C^CStopping ...
Stopping ...
Exiting


```

**Comment by distler** [comment]
Hmm.

Untested with Rack 2.x. Try the [updated Gemfile](https://github.com/parasew/instiki/blob/master/Gemfile), which locks Rack at 1.4.5 (which is known to work).

**Comment by SL-RU** [comment]
Thanks! It's works now! Awesome!
