### ISSUE TITLE
Unable to Install of Mac 10.14.6

### ISSUE THREAD

**Issue by turnersr** [parasew/instiki#62]
Hello,

I am trying to install on macOS Mojave. The issue I get in the end is 

```
$ ./instiki --daemon
/Library/Ruby/Site/2.3.0/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version': You must use Bundler 2 or greater with this lockfile. (Bundler::LockfileError)
	from /Library/Ruby/Site/2.3.0/bundler/lockfile_parser.rb:95:in `initialize'
	from /Library/Ruby/Site/2.3.0/bundler/definition.rb:83:in `new'
	from /Library/Ruby/Site/2.3.0/bundler/definition.rb:83:in `initialize'
	from /Library/Ruby/Site/2.3.0/bundler/dsl.rb:234:in `new'
	from /Library/Ruby/Site/2.3.0/bundler/dsl.rb:234:in `to_definition'
	from /Library/Ruby/Site/2.3.0/bundler/dsl.rb:13:in `evaluate'
	from /Library/Ruby/Site/2.3.0/bundler/definition.rb:34:in `build'
	from /Library/Ruby/Site/2.3.0/bundler.rb:135:in `definition'
	from /Library/Ruby/Site/2.3.0/bundler.rb:101:in `setup'
	from /Users/wintermute/instiki-0.30.1/config/preinitializer.rb:18:in `<top (required)>'
	from /Users/wintermute/instiki-0.30.1/config/boot.rb:43:in `load'
	from /Users/wintermute/instiki-0.30.1/config/boot.rb:43:in `preinitialize'
	from /Users/wintermute/instiki-0.30.1/config/boot.rb:25:in `boot!'
	from /Users/wintermute/instiki-0.30.1/config/boot.rb:139:in `<top (required)>'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/wintermute/instiki-0.30.1/script/server:3:in `<top (required)>'
	from ./instiki:6:in `load'
	from ./instiki:6:in `<main>'
```

**Comment by distler** [comment]
1. I assume you followed the instructions [here](https://golem.ph.utexas.edu/wiki/instiki/show/Installation)?
2. Are you using version 0.30.1 or Github HEAD ?
3. Could you say what `bundle --version` reports?
4. If it's older than 2.0, then you may need to reinstall, but do a
    ~~~~~
    bundle install --path vendor/bundle
    ~~~~~
    instead of
    ~~~~~
    ruby bundle install --path vendor/bundle
    ~~~~~

**Comment by turnersr** [comment]
I followed those instructions. I tried both master branch from GitHub as well as the latest release. I get the same error. 

```
bundle --version
Bundler version 2.0.2
```

**Comment by distler** [comment]
Well, you evidently have an older (pre-2.0) version of Bundler installed at `/Library/Ruby/Site/2.3.0/`. I don't know how it go there (my Mojave installation doesn't have one), but I am reluctant to tell you to get rid of it.

Instead, you might try doing `gem install bundler` which should upgrade the version of Bundler seen by your system ruby to 2.0.x.

**Comment by turnersr** [comment]
So, I was able to get the server started on MacOs:

```
bundle exec instiki build
```

But now I have very odd errors on the wiki page that my changes don't save. I attached a screenshot. 

<img width="998" alt="Screen Shot 2019-08-13 at 7 29 50 PM" src="https://user-images.githubusercontent.com/743360/62963301-ff0f9700-be00-11e9-8930-6ee9c568110b.png">

This is also very oddly the exact same type of error when I use the following Dockerfile:

```
FROM ubuntu:18.04
RUN apt-get update 
RUN apt-get install -y ruby ruby-dev ri ruby-openssl ruby-sqlite3 rake libxslt1-dev ruby-libxml libsqlite3-dev libxml2-dev swig flex bison git 
WORKDIR /wiki/
RUN git clone https://github.com/parasew/instiki.git
WORKDIR /wiki/instiki/
RUN ruby bundle install --path vendor/bundle
EXPOSE 2500
CMD ["./instiki"]
```

Here the log information:

```
bundle exec instiki build
=> Booting Thin
=> Rails 2.3.18 application starting on http://0.0.0.0:2500
=> Call with -d to detach
=> Ctrl-C to shutdown server
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on 0.0.0.0:2500, CTRL+C to stop


Processing WikiController#index (for 127.0.0.1 at 2019-08-13 19:29:34) [GET]
Redirected to http://0.0.0.0:2500/wiki/show/HomePage
Completed in 65ms (DB: 0) | 302 Found [http://0.0.0.0/]


Processing WikiController#index (for 127.0.0.1 at 2019-08-13 19:29:34) [GET]
Redirected to http://0.0.0.0:2500/wiki/show/HomePage
Completed in 65ms (DB: 0) | 302 Found [http://0.0.0.0/]


Processing WikiController#show (for 127.0.0.1 at 2019-08-13 19:29:34) [GET]
  Parameters: {"web"=>"wiki", "id"=>"HomePage"}
Reading page 'HomePage' from web 'wiki'
Page 'HomePage'  found
Cached fragment hit: views/wiki/show/HomePage (0.5ms)
Filter chain halted as [#<ActionController::Filters::AroundFilter:0x00007fd27bee0228 @kind=:filter, @method=#<Proc:0x00007fd27bee0520@/Users/wintermute/instiki/vendor/rails/actionpack/lib/action_controller/caching/actions.rb:64>, @identifier=nil, @options={:only=>#<Set: {"show", "published", "authors", "tex", "s5", "print", "recently_revised", "list", "file_list", "source", "history", "revision", "atom_with_content", "atom_with_headlines", "atom_with_changes"}>, :if=>#<Proc:0x00007fd27bee0728@/Users/wintermute/instiki/app/controllers/wiki_controller.rb:15>, :unless=>nil}>] did_not_yield.
Completed in 5ms (View: 0, DB: 0) | 200 OK [http://0.0.0.0/wiki/show/HomePage]


Processing WikiController#show (for 127.0.0.1 at 2019-08-13 19:29:34) [GET]
  Parameters: {"web"=>"wiki", "id"=>"HomePage"}
Reading page 'HomePage' from web 'wiki'
Page 'HomePage'  found
Cached fragment hit: views/wiki/show/HomePage (0.5ms)
Filter chain halted as [#<ActionController::Filters::AroundFilter:0x00007fd27bee0228 @kind=:filter, @method=#<Proc:0x00007fd27bee0520@/Users/wintermute/instiki/vendor/rails/actionpack/lib/action_controller/caching/actions.rb:64>, @identifier=nil, @options={:only=>#<Set: {"show", "published", "authors", "tex", "s5", "print", "recently_revised", "list", "file_list", "source", "history", "revision", "atom_with_content", "atom_with_headlines", "atom_with_changes"}>, :if=>#<Proc:0x00007fd27bee0728@/Users/wintermute/instiki/app/controllers/wiki_controller.rb:15>, :unless=>nil}>] did_not_yield.
Completed in 5ms (View: 0, DB: 0) | 200 OK [http://0.0.0.0/wiki/show/HomePage]
```

Thank you!

**Comment by distler** [comment]
So, wait,
~~~~~
bundle exec instiki build
~~~~~
"works", but
~~~~~
./instiki
~~~~~
doesn't?

And what exactly is happening when you try to edit/save a page?

**Comment by distler** [comment]
>But now I have very odd errors on the wiki page that my changes can't overwrite. I attached a screenshot.

[Apparently](https://golem.ph.utexas.edu/category/2006/09/texnical_issues.html#c056472), this is an incompatibility with the [Grammarly](https://www.grammarly.com/) browser extension.

**Comment by distler** [comment]
Closing for lack of user feedback.
